FROM tensorflow/tensorflow:2.20.0


WORKDIR /app

# Copy requirements except tensorflow
COPY requirements.txt .  
RUN pip install --no-cache-dir -r requirements.txt

COPY app.py .
COPY regression_model.h5 .

EXPOSE 8000

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
